const booksData = [
  {
    id: 1,
    title: "The Lighthouse Keeper",
    author: "Mara Ellison",
    genre: "Fiction",
    price: 18.00,
    originalPrice: 24.00,
    rating: 4.8,
    reviewsCount: 124,
    pages: 312,
    publishedYear: 2023,
    publisher: "Harbor & Vale",
    language: "English",
    isbn: "978-1-23456-001-2",
    description: "A widowed keeper and a runaway girl share a winter on a remote island, learning what it means to keep a light burning for someone else.",
    coverColor: "#284e3a",
    textColor: "#ffffff",
    tag: "BESTSELLER",
    isStaffPick: true
  },
  {
    id: 2,
    title: "Ashes in the Archive",
    author: "J. P. Crowe",
    genre: "Mystery",
    price: 15.50,
    originalPrice: null,
    rating: 4.4,
    reviewsCount: 89,
    pages: 280,
    publishedYear: 2022,
    publisher: "Blackwood Press",
    language: "English",
    isbn: "978-1-23456-002-9",
    description: "When a fire destroys the historic city archive, a young archivist discovers a charred manuscript containing details of a century-old unsolved murder.",
    coverColor: "#4a627a",
    textColor: "#ffffff",
    tag: "BESTSELLER",
    isStaffPick: true
  },
  {
    id: 3,
    title: "Salt & Other Small Gods",
    author: "Imani Ghalib",
    genre: "Poetry",
    price: 13.00,
    originalPrice: null,
    rating: 4.0,
    reviewsCount: 56,
    pages: 144,
    publishedYear: 2024,
    publisher: "Vesper Books",
    language: "English",
    isbn: "978-1-23456-003-6",
    description: "A stunning debut collection of prose and poetry exploring legacy, migration, and the quiet divinity found in the mundane elements of coastal life.",
    coverColor: "#8b4864",
    textColor: "#ffffff",
    tag: "NEW",
    isStaffPick: false
  },
  {
    id: 4,
    title: "A House of Borrowed Light",
    author: "Sofia Marchetti",
    genre: "Sci-Fi",
    price: 17.25,
    originalPrice: 22.00,
    rating: 4.5,
    reviewsCount: 112,
    pages: 402,
    publishedYear: 2023,
    publisher: "Apex Publishing",
    language: "English",
    isbn: "978-1-23456-004-3",
    description: "In a city where sunlight is a privatized commodity, a low-level solar technician starts stealing photons to light up an underground greenhouse.",
    coverColor: "#584a75",
    textColor: "#ffffff",
    tag: "NEW",
    isStaffPick: false
  },
  {
    id: 5,
    title: "Everything the River Took",
    author: "Ada Fenwick",
    genre: "Mystery",
    price: 18.75,
    originalPrice: null,
    rating: 4.8,
    reviewsCount: 145,
    pages: 350,
    publishedYear: 2021,
    publisher: "Harbor & Vale",
    language: "English",
    isbn: "978-1-23456-005-0",
    description: "When the worst drought in a generation shrinks the local riverbed, it reveals a rusted vehicle containing secrets a small town thought were buried forever.",
    coverColor: "#7c5943",
    textColor: "#ffffff",
    tag: "BESTSELLER",
    isStaffPick: true
  },
  {
    id: 6,
    title: "Orbital Driftwood",
    author: "Nadia Vance",
    genre: "Sci-Fi",
    price: 21.00,
    originalPrice: null,
    rating: 4.7,
    reviewsCount: 78,
    pages: 328,
    publishedYear: 2023,
    publisher: "Apex Publishing",
    language: "English",
    isbn: "978-1-23456-006-7",
    description: "An elegant sci-fi epic about the junk collectors orbiting Saturn who stumble upon an inactive alien probe that begins to mirror their thoughts.",
    coverColor: "#467a80",
    textColor: "#ffffff",
    tag: null,
    isStaffPick: false
  },
  {
    id: 7,
    title: "Pip and the Paper Moon",
    author: "Lena Hart",
    genre: "Children",
    price: 11.50,
    originalPrice: null,
    rating: 4.9,
    reviewsCount: 210,
    pages: 48,
    publishedYear: 2024,
    publisher: "Caterpillar Press",
    language: "English",
    isbn: "978-1-23456-007-4",
    description: "A beautifully illustrated story of a little rabbit who builds a ladder to the moon, discovering that sometimes the things we reach for are already inside us.",
    coverColor: "#b88c42",
    textColor: "#ffffff",
    tag: "BESTSELLER",
    isStaffPick: false
  },
  {
    id: 8,
    title: "The Quiet Economy",
    author: "Daniel Roth",
    genre: "Non-fiction",
    price: 19.99,
    originalPrice: null,
    rating: 4.2,
    reviewsCount: 64,
    pages: 290,
    publishedYear: 2022,
    publisher: "Beacon Press",
    language: "English",
    isbn: "978-1-23456-008-1",
    description: "An eye-opening analysis of barter networks and informal trade communities that thrive in the shadows of modern digital commerce.",
    coverColor: "#66483f",
    textColor: "#ffffff",
    tag: null,
    isStaffPick: false
  },
  {
    id: 9,
    title: "Hands in the Soil",
    author: "Stella Lindqvist",
    genre: "Non-fiction",
    price: 23.00,
    originalPrice: null,
    rating: 4.3,
    reviewsCount: 42,
    pages: 256,
    publishedYear: 2023,
    publisher: "Beacon Press",
    language: "English",
    isbn: "978-1-23456-009-8",
    description: "A memoir and manifesto on community gardening, local food sovereignty, and the profound mental health benefits of connecting with the earth.",
    coverColor: "#395b45",
    textColor: "#ffffff",
    tag: null,
    isStaffPick: false
  },
  {
    id: 10,
    title: "The Saltmarsh Murders",
    author: "Edmond Pryce",
    genre: "Mystery",
    price: 16.00,
    originalPrice: null,
    rating: 4.1,
    reviewsCount: 73,
    pages: 310,
    publishedYear: 2021,
    publisher: "Blackwood Press",
    language: "English",
    isbn: "978-1-23456-010-4",
    description: "A gripping atmospheric mystery set in a fog-bound coastal village where old family feuds resurface with the discovery of a body in the saltmarshes.",
    coverColor: "#783838",
    textColor: "#ffffff",
    tag: null,
    isStaffPick: false
  },
  {
    id: 11,
    title: "Threads of the Void",
    author: "Kei Tanaka",
    genre: "Sci-Fi",
    price: 20.50,
    originalPrice: null,
    rating: 4.6,
    reviewsCount: 95,
    pages: 368,
    publishedYear: 2024,
    publisher: "Apex Publishing",
    language: "English",
    isbn: "978-1-23456-011-1",
    description: "A mind-bending space opera examining quantum entanglement as a communication tool across light-years and the societal divisions it triggers.",
    coverColor: "#475975",
    textColor: "#ffffff",
    tag: "NEW",
    isStaffPick: false
  },
  {
    id: 12,
    title: "The Button Thief",
    author: "Marco Diaz",
    genre: "Children",
    price: 10.99,
    originalPrice: null,
    rating: 4.7,
    reviewsCount: 130,
    pages: 36,
    publishedYear: 2023,
    publisher: "Caterpillar Press",
    language: "English",
    isbn: "978-1-23456-012-8",
    description: "Follow the delightful nighttime escapades of a tiny field mouse who collects lost buttons to construct a miniature amusement park.",
    coverColor: "#9e774c",
    textColor: "#ffffff",
    tag: "NEW",
    isStaffPick: false
  },
  {
    id: 13,
    title: "Echoes of the Loom",
    author: "Clara Dupont",
    genre: "Poetry",
    price: 14.50,
    originalPrice: null,
    rating: 4.3,
    reviewsCount: 38,
    pages: 120,
    publishedYear: 2023,
    publisher: "Vesper Books",
    language: "English",
    isbn: "978-1-23456-013-5",
    description: "A lyrical exploration of weaving metaphors, family history, and the intergenerational threads that connect us to our ancestors' stories.",
    coverColor: "#804868",
    textColor: "#ffffff",
    tag: null,
    isStaffPick: false
  },
  {
    id: 14,
    title: "Beyond the Horizon",
    author: "Arthur Sterling",
    genre: "Biography",
    price: 25.00,
    originalPrice: null,
    rating: 4.9,
    reviewsCount: 167,
    pages: 512,
    publishedYear: 2022,
    publisher: "Beacon Press",
    language: "English",
    isbn: "978-1-23456-014-2",
    description: "The definitive, sweeping biography of an early 20th-century polar explorer who charted uncharted territories and survived years trapped in ice.",
    coverColor: "#2c505c",
    textColor: "#ffffff",
    tag: null,
    isStaffPick: false
  }
];

const genresData = [
  { name: "Fiction", color: "#8a4f3e", count: 3 },
  { name: "Mystery", color: "#5c7294", count: 3 },
  { name: "Sci-Fi", color: "#568285", count: 3 },
  { name: "Poetry", color: "#8a4562", count: 2 },
  { name: "Children", color: "#c48e47", count: 2 },
  { name: "Non-fiction", color: "#6a5875", count: 2 },
  { name: "Biography", color: "#4f6e63", count: 1 }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { booksData, genresData };
} else {
  window.booksData = booksData;
  window.genresData = genresData;
}
